services:
  yagoutpay-python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yagoutpay-python
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - ./demo:/app/demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
